/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/connect': typeof ConnectRoute
  '/results': typeof ResultsRoute
  '/profile/$username': typeof ProfileUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/connect': typeof ConnectRoute
  '/results': typeof ResultsRoute
  '/profile/$username': typeof ProfileUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/connect': typeof ConnectRoute
  '/results': typeof ResultsRoute
  '/profile/$username': typeof ProfileUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analyze' | '/connect' | '/results' | '/profile/$username'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analyze' | '/connect' | '/results' | '/profile/$username'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/connect'
    | '/results'
    | '/profile/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  ConnectRoute: typeof ConnectRoute
  ResultsRoute: typeof ResultsRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  ConnectRoute: ConnectRoute,
  ResultsRoute: ResultsRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
