/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as ApiPublicSpotifyCallbackRouteImport } from './routes/api/public/spotify/callback'
import { Route as ApiPublicSpotifyLoginRouteImport } from './routes/api/public/spotify/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSpotifyCallbackRoute =
  ApiPublicSpotifyCallbackRouteImport.update({
    id: '/api/public/spotify/callback',
    path: '/api/public/spotify/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSpotifyLoginRoute = ApiPublicSpotifyLoginRouteImport.update({
  id: '/api/public/spotify/login',
  path: '/api/public/spotify/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/connect': typeof ConnectRoute
  '/results': typeof ResultsRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/api/public/spotify/callback': typeof ApiPublicSpotifyCallbackRoute
  '/api/public/spotify/login': typeof ApiPublicSpotifyLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/connect': typeof ConnectRoute
  '/results': typeof ResultsRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/api/public/spotify/callback': typeof ApiPublicSpotifyCallbackRoute
  '/api/public/spotify/login': typeof ApiPublicSpotifyLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/connect': typeof ConnectRoute
  '/results': typeof ResultsRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/api/public/spotify/callback': typeof ApiPublicSpotifyCallbackRoute
  '/api/public/spotify/login': typeof ApiPublicSpotifyLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/connect'
    | '/results'
    | '/profile/$username'
    | '/api/public/spotify/callback'
    | '/api/public/spotify/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/connect'
    | '/results'
    | '/profile/$username'
    | '/api/public/spotify/callback'
    | '/api/public/spotify/login'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/connect'
    | '/results'
    | '/profile/$username'
    | '/api/public/spotify/callback'
    | '/api/public/spotify/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  ConnectRoute: typeof ConnectRoute
  ResultsRoute: typeof ResultsRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ApiPublicSpotifyCallbackRoute: typeof ApiPublicSpotifyCallbackRoute
  ApiPublicSpotifyLoginRoute: typeof ApiPublicSpotifyLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/spotify/callback': {
      id: '/api/public/spotify/callback'
      path: '/api/public/spotify/callback'
      fullPath: '/api/public/spotify/callback'
      preLoaderRoute: typeof ApiPublicSpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/spotify/login': {
      id: '/api/public/spotify/login'
      path: '/api/public/spotify/login'
      fullPath: '/api/public/spotify/login'
      preLoaderRoute: typeof ApiPublicSpotifyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  ConnectRoute: ConnectRoute,
  ResultsRoute: ResultsRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ApiPublicSpotifyCallbackRoute: ApiPublicSpotifyCallbackRoute,
  ApiPublicSpotifyLoginRoute: ApiPublicSpotifyLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
